# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZWZhYWI0YWJkMzg0ZTgxZDc3ZTNiZTMwYzQ5YzlmZjQ0ZWY2NTg0ZjZhNWEzMWZmMGE1YWMzMWE5ODFhYTA1NzdkNjBhZDQ1YTFiYzA3Yjc5OTM3ZmE2ZGVkNGUwYzU5M2U2ZWJmMmE2NjkzNDdkMzE5YzM5ZWJhNTdmYmQ1MWE=
