spring:
  application:
    name: droolsrules

  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-4o-mini